# Generated by Django 3.2.21 on 2023-11-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='country',
        ),
        migrations.AddField(
            model_name='category',
            name='country',
            field=models.ManyToManyField(to='api.Country'),
        ),
    ]
