# Generated by Django 3.2.21 on 2023-11-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_brand_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='name',
            new_name='description',
        ),
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
