# Generated by Django 3.2.21 on 2023-12-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20231130_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='extension',
            field=models.CharField(default='+999', max_length=6),
            preserve_default=False,
        ),
    ]
