# Generated by Django 3.2.21 on 2023-12-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_country_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='country',
            field=models.ManyToManyField(blank=True, null=True, to='api.Country'),
        ),
    ]
