# Generated by Django 3.2.21 on 2023-12-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_category_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='country',
            field=models.ManyToManyField(blank=True, null=True, to='api.Country'),
        ),
    ]
