# Generated by Django 3.2.21 on 2023-12-09 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_brand_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='topStore',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='api.brand'),
        ),
    ]
